apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: akka-cluster
        image: lkysow/akka-cluster
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CLUSTER_ROLES
          value: frontend
        ports:
        - containerPort: 8080
        - containerPort: 2551
        resources:
          requests:
            cpu: 0.5
            memory: 512Mi
          limits:
            cpu: 1.5
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
---
kind: Service
apiVersion: v1
metadata:
  name: nothotdog
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: akka-cluster
        image: lkysow/akka-cluster
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CLUSTER_ROLES
          value: backend
        ports:
        - containerPort: 2551
        resources:
          requests:
            cpu: 0.5
            memory: 512Mi
          limits:
            cpu: 1.5
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 2551
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 2551
          initialDelaySeconds: 15
          periodSeconds: 20
